In [1]:
import pandavro as pdx
import pandas as pd
import matplotlib as plt
from matplotlib import pyplot as plt, ticker as mticker
import json
import numpy as np

In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option('display.max_colwidth', None)

In [3]:
filename='../../projects/benchmark/loadtest/noop_bolcom_c1000000_t50_eager_cpu.avro'

df = pdx.from_avro(filename)
len(df)

17976

In [4]:
df2 = df.explode('interactions')
latency_df = df2['interactions'].apply(pd.Series )

In [5]:
latency_df['DateTime'] = pd.to_datetime(latency_df['timestamp_epoch_millis'], unit='ms')
filtered_df = latency_df[latency_df['DateTime'] >= (latency_df['DateTime'].min() + pd.Timedelta(seconds=5))]

In [18]:
np.percentile(filtered_df['latency_millis'], q=[0.9, 0.95, 0.99])

array([18., 18., 18.])

In [19]:
np.percentile(filtered_df['preprocessing_millis'], q=[0.9, 0.95, 0.99])

array([0.14874087, 0.14912446, 0.14936637])

In [20]:
np.percentile(filtered_df['inferencing_millis'], q=[0.9, 0.95, 0.99])

array([7.09410105, 7.1090317 , 7.12396969])

In [21]:
np.percentile(filtered_df['processing_millis'], q=[0.9, 0.95, 0.99])

array([0.06335149, 0.06347405, 0.063563  ])