In [1]:
import pandavro as pdx
import pandas as pd
import matplotlib as plt
from matplotlib import pyplot as plt, ticker as mticker
import json
import numpy as np

In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option('display.max_colwidth', None)

In [3]:
filename='../../projects/benchmark/loadtest/noop_bolcom_c1000000_t50_eager_cpu.avro'

df = pdx.from_avro(filename)
len(df)

17976

In [4]:
df2 = df.explode('interactions')
latency_df = df2['interactions'].apply(pd.Series )

In [5]:
latency_df['DateTime'] = pd.to_datetime(latency_df['timestamp_epoch_millis'], unit='ms')
filtered_df = latency_df[latency_df['DateTime'] >= (latency_df['DateTime'].min() + pd.Timedelta(seconds=5))]

In [18]:
np.percentile(filtered_df['latency_millis'], q=[0.9, 0.95, 0.99])

array([18., 18., 18.])

In [19]:
np.percentile(filtered_df['preprocessing_millis'], q=[0.9, 0.95, 0.99])

array([0.14874087, 0.14912446, 0.14936637])

In [20]:
np.percentile(filtered_df['inferencing_millis'], q=[0.9, 0.95, 0.99])

array([7.09410105, 7.1090317 , 7.12396969])

In [21]:
np.percentile(filtered_df['processing_millis'], q=[0.9, 0.95, 0.99])

array([0.06335149, 0.06347405, 0.063563  ])

In [22]:
latency_df

input  \
0                                             [185535]   
0                                     [185535, 630674]   
0                             [185535, 630674, 188136]   
0                     [185535, 630674, 188136, 994147]   
1                                             [998704]   
...                                                ...   
17974                          [769121, 893410, 35426]   
17974                  [769121, 893410, 35426, 558032]   
17974          [769121, 893410, 35426, 558032, 193287]   
17974  [769121, 893410, 35426, 558032, 193287, 826231]   
17975                                         [908612]   

                                                                                                                                                                       output  \
0      [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
0      [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
0      [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
0      [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
1      [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
...                                                                                                                                                                       ...   
17974  [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
17974  [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
17974  [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
17974  [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   
17975  [171471, 979382, 957956, 730240, 307302, 269623, 528550, 844493, 498417, 285165, 596446, 786909, 99594, 505768, 783765, 358086, 561834, 75703, 680575, 785607, 582257]   

       status  latency_millis  timestamp_epoch_millis  preprocessing_millis  \
0         200              52           1681850329388              0.402865   
0         200              37           1681850330368              0.284900   
0         200              20           1681850331367              0.264438   
0         200              21           1681850332367              0.288287   
1         200              48           1681850330391              0.223307   
...       ...             ...                     ...                   ...   
17974     200              27           1681850911879              0.205776   
17974     200              27           1681850953922              6.656055   
17974     200              24           1681851000383              0.822693   
17974     200              20           1681851051280              0.182596   
17975     200              27           1681851051301              0.228389   

       inferencing_millis  processing_millis                DateTime  
0                7.737338           0.112003 2023-04-18 20:38:49.388  
0               10.693309           0.109706 2023-04-18 20:38:50.368  
0                6.968655           0.105312 2023-04-18 20:38:51.