In [51]:
import torch
import torch.nn.functional as fn
import numpy as np

In [52]:
min_item_id=0
max_item_id=10_000
max_session_length=43
batch_size=2
torch.empty(min_item_id, max_item_id, (batch_size, max_session_length))

TypeError: empty(): argument 'size' must be tuple of SymInts, but found element of type tuple at pos 3

In [23]:
batch_size=2
max_session_length=43
mask = torch.empty(batch_size, max_session_length)

In [24]:
mask

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
items = torch.randint(0, max_item_id, (batch_size, max_session_length))
print(items)
items = fn.pad(items, (1, 0))
print(items)

tensor([[ 837, 4598, 1324, 8390, 8858,  631, 1229, 9958, 9449, 7593, 8834, 1217,
         1978, 8684, 2381, 6351, 1199, 2637,  427, 2147, 6605, 5571, 9489, 7782,
         8752, 3776, 9003,  519, 5336, 3821, 3586, 6803, 2594, 8675, 6688, 9987,
         2410, 3674, 1008, 5492, 3373, 3144, 1520],
        [ 119, 5668, 4119, 3690, 9523,  527, 2163, 9602, 1637, 4707, 2479, 3134,
         7552, 8736, 1954, 5516, 5344, 5987, 2665, 2273, 9009, 7840, 7602, 2132,
         1100, 4191, 8855,  822, 2189, 4485,  185, 9385, 3053, 1962, 7280, 2040,
         9653, 5352, 2261, 6545, 2029, 8899, 6643]])
tensor([[   0,  837, 4598, 1324, 8390, 8858,  631, 1229, 9958, 9449, 7593, 8834,
         1217, 1978, 8684, 2381, 6351, 1199, 2637,  427, 2147, 6605, 5571, 9489,
         7782, 8752, 3776, 9003,  519, 5336, 3821, 3586, 6803, 2594, 8675, 6688,
         9987, 2410, 3674, 1008, 5492, 3373, 3144, 1520],
        [   0,  119, 5668, 4119, 3690, 9523,  527, 2163, 9602, 1637, 4707, 2479,
         3134, 7552, 8736, 

In [30]:
items

tensor([[0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
         1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0]])

In [40]:
fn.pad(items, (0, 5))

tensor([[   0,  837, 4598, 1324, 8390, 8858,  631, 1229, 9958, 9449, 7593, 8834,
         1217, 1978, 8684, 2381, 6351, 1199, 2637,  427, 2147, 6605, 5571, 9489,
         7782, 8752, 3776, 9003,  519, 5336, 3821, 3586, 6803, 2594, 8675, 6688,
         9987, 2410, 3674, 1008, 5492, 3373, 3144, 1520,    0,    0,    0,    0,
            0],
        [   0,  119, 5668, 4119, 3690, 9523,  527, 2163, 9602, 1637, 4707, 2479,
         3134, 7552, 8736, 1954, 5516, 5344, 5987, 2665, 2273, 9009, 7840, 7602,
         2132, 1100, 4191, 8855,  822, 2189, 4485,  185, 9385, 3053, 1962, 7280,
         2040, 9653, 5352, 2261, 6545, 2029, 8899, 6643,    0,    0,    0,    0,
            0]])

In [160]:
item_seq_lengths = np.zeros(batch_size, dtype=int)
item_seqs = np.zeros((batch_size, max_session_length), dtype=int)

In [161]:
item_seq_lengths

array([0, 0])

In [162]:
for idx in range(batch_size):
    session_length = np.random.randint(1, max_session_length + 1)
    item_seq = np.random.randint(0, max_item_id + 1, session_length) 
    item_seq.resize(max_session_length, refcheck=False)
    item_seqs[idx] = item_seq
    item_seq_lengths[idx] = session_length


In [163]:
print(torch.as_tensor(item_seq_lengths))
print(torch.as_tensor(item_seqs))

tensor([20, 17])
tensor([[7703, 1335, 5095, 7942, 1156, 6938, 3842, 1168, 2691, 9394, 7012,   16,
         3460, 6371, 2717, 5316, 3316, 4821, 9705, 7879,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0],
        [1160, 5893,  496, 3549, 2694, 7428, 4567, 4739, 1956, 3511, 9451, 9911,
          990, 4356, 6947, 8591, 8988,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0]])
