In [1]:
import numpy as np
import math
import scipy.stats as st
from scipy.stats._continuous_distns import _distn_names
import pandas as pd

In [2]:
df = pd.read_csv('../../projects/data/bolcom-clicks-35m_test.txt', sep='\t')
df

rng = np.random.default_rng()

distribution_name = 'powerlaw'
distribution = getattr(st, distribution_name)

FileNotFoundError: [Errno 2] No such file or directory: '../../projects/data/bolcom-clicks-35m_test.txt'

In [3]:
# Observed frequencies to observed probability
f_obs = df.groupby('SessionId').size().to_numpy()
f_obs = np.sort(f_obs)
f_obs

# Fit a distribution to a frequency
s_fit_params = distribution.fit(f_obs)
s_fit_params


NameError: name 'df' is not defined

In [4]:
# Observed frequencies to observed probability
f_obs = df.groupby('ItemId').size().to_numpy()
f_obs = np.sort(f_obs)
f_obs

# Fit a distribution to a frequency
i_fit_params = distribution.fit(f_obs)
i_fit_params


NameError: name 'df' is not defined

In [5]:
C = 50_000_000
f_new = distribution.rvs(*i_fit_params, size=C)
f_new = np.ceil(f_new).astype(int)
f_new

NameError: name 'distribution' is not defined

In [6]:
p_obs = f_new / np.sum(f_new)
n_samples = 350_000
random_items = rng.choice(len(p_obs), 
                          size=n_samples,
                          replace=True,
                          p = p_obs)

NameError: name 'f_new' is not defined

In [7]:
random_items

NameError: name 'random_items' is not defined

In [51]:
import torch
session_length = 2
max_seq_length = 43
items = np.array([123, 234])
next_item = 345

In [40]:
evolving_items.resize(max_seq_length, refcheck=False)
evolving_items

array([123, 234,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0])

In [61]:
import torch

items = torch.tensor([123, 234, 345, 456, 567])
tril_items = torch.tril(items.expand(len(items), len(items)), diagonal=0)
print(tril_items)

tensor([[123,   0,   0,   0,   0],
        [123, 234,   0,   0,   0],
        [123, 234, 345,   0,   0],
        [123, 234, 345, 456,   0],
        [123, 234, 345, 456, 567]])


In [60]:
tril_items = torch.tril(items.expand(len(items), len(items)), diagonal=0)
print(tril_items)

tensor([[123,   0,   0,   0,   0],
        [123, 234,   0,   0,   0],
        [123, 234, 345,   0,   0],
        [123, 234, 345, 456,   0],
        [123, 234, 345, 456, 567]])


In [81]:
items.expand(len(items), len(items))

tensor([[123, 234, 345, 456, 567],
        [123, 234, 345, 456, 567],
        [123, 234, 345, 456, 567],
        [123, 234, 345, 456, 567],
        [123, 234, 345, 456, 567]])

In [62]:
from torch.utils.data import Dataset
import numpy as np
import scipy.stats as st
import torch



In [63]:
rng = np.random.default_rng()

In [71]:
item_seq = rng.choice(2,
                                       size=1,
                                       replace=True,
                                       p=[0.5,0.5])
item_seq

array([1], dtype=int64)

In [78]:
evolving_items = torch.tensor(item_seq[:-1])

In [88]:
tril_items = torch.tril(items.expand(len(items), len(items)), diagonal=0)
tril_items

tensor([[123,   0,   0,   0,   0],
        [123, 234,   0,   0,   0],
        [123, 234, 345,   0,   0],
        [123, 234, 345, 456,   0],
        [123, 234, 345, 456, 567]])

In [87]:
tril_items[2]

tensor([123, 234, 345,   0,   0])

In [89]:
idx = 4